logLevel: INFO
localRange: 100 # blocks
quitAfterKick: false
asyncPermissionCache: 300 # seconds
messages:
    names:
        +player: '{0}§f' # 0 = Player Display Name
        +other: '({0}§f)' # 0 = Sender Name
        +console: '§5§oConsole:Ed§f' # 0 = Console Name
    chat:  '§8{0,time,HH:mm:ss} §8<§f{1}§8>§f {2}' # 1 = Formatted Sender Name, 2 = Message
    me:    '§8{0,time,HH:mm:ss} §f* {1} {2}' # 1 = Formatted Sender Name, 2 = Message
    tell:  '§8{0,time,HH:mm:ss} §f@§8§o{2} §8<§f{1}§8>§f {3}' # 1 = Formatted Sender Name, 2 = Formatted Recipient Name, 3 = Message
    local: '§8{0,time,HH:mm:ss} #§6Local§r §8<§f{1}§8>§f {2}' # 1 = Formatted Sender Name, 2 = Message
    say:   '§8{0,time,HH:mm:ss} §8<§f{1}§8>§f {2}' # 1 = Formatted Sender Name, 2 = Message
    join:  '§8{0,time,HH:mm:ss}§7 {1} §6joined§7 the server' # 1 = Formatted Name
    quit:  '§8{0,time,HH:mm:ss}§7 {1} §9left§7 the server' # 1 = Formatted Name
    death: '§8{0,time,HH:mm:ss} {2}' # 1 = Formatted Name, 2 = Death Message
    kick: # 1 = Formatted Name, 2 = Formatted Reason
        broadcast: '§8{0,time,HH:mm:ss}§f {1} was §ckicked§r ({2})'
        +reason: '§o{0}§f' # 1 = Reason
    login: # 1 = Formatted Name, 2 = Formatted Reason
        KICK_BANNED:
            +reason: '§o{0}s§r' # 0 = Reason
        KICK_FULL:
            +reason: '§o{0}§r' # 0 = Reason
        KICK_WHITELIST:
            broadcast: '§8{0,time,HH:mm:ss}§r §e§oDisconnected§r {1} §e§odue to whitelist'
            +reason: '§o{0}§r' # 0 = Reason
        KICK_OTHER:
            +reason: '§o{0}§r' # 0 = Reason
    requiresArgument: '-> §7Required §cargument missing§7: §o{1}' # 1 = Argument Name
    requiresPlayer: '-> §cOnly in-game players§7 can use the {1} command' # 1 = Command Label
    playerNotFound: '-> §7Player §enot found§7: §o{1}' # 1 = <Player>
    replyNotAvailable: '-> §eNo one§7 to reply to'
    nick: '-> §2Set display name§7 for §o{1}§7 to §r{2}' # 1 = Player Name, 2 = Player Display Name
    reload: '-> §7{1} plugin §2reloaded' # 1 = Plugin
version: @VERSION@