name: MessageFormatter
version: @VERSION@
description: Chat message formatting
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/MessageFormatter
main: edgruberman.bukkit.messageformatter.Main
commands:
    'messageformatter:say':
        description: Broadcast a message to all players
        permission: messageformatter.say
        usage: /<command> <Message>
    'messageformatter:me':
        description: Broadcast an action to all players
        permission: messageformatter.me
        usage: /<command> <Message>
    'messageformatter:tell':
        aliases: [tell, t, '@', whisper, w]
        description: Send a private message to a player
        permission: messageformatter.tell
        usage: /<command> <Player> <Message>
    'messageformatter:reply':
        aliases: [reply, r]
        description: Send a private message to the last player that sent you a private message
        permission: messageformatter.reply
        usage: /<command> <Message>
    'messageformatter:local':
        aliases: [local, l]
        description: Broadcast a message only to players close by
        permission: messageformatter.local
        usage: /<command> <Message>
    'messageformatter:broadcast':
        aliases: [broadcast]
        description: Broadcast a message to all players anonymously
        permission: messageformatter.broadcast
        usage: /<command> <Message>
    'messageformatter:send':
        aliases: [send]
        description: Send a private message to a player anonymously
        permission: messageformatter.send
        usage: /<command> <Player> <Message>
    'messageformatter:nick':
        aliases: [nick]
        description: Change player display name
        permission: messageformatter.nick
        usage: /<command> <Player>[ <Display>]
    'messageformatter:reload':
        description: Reload MessageFormatterplugin
        permission: messageformatter.reload
permissions:
    messageformatter.user:
        description: Can use basic features of MessageFormatter plugin
        default: true
        children:
            messageformatter.say: true
            messageformatter.me: true
            messageformatter.tell: true
            messageformatter.reply: true
            messageformatter.local: true
    messageformatter.admin:
        description: Can use administrative features of MessageFormatter plugin
        default: op
        children:
            messageformatter.user: true
            messageformatter.colors: true
            messageformatter.broadcast: true
            messageformatter.send: true
            messageformatter.nick: true
            messageformatter.reload: true
    messageformatter.colors:
        description: Can use ampersand color codes in commands and chat
        default: false
    messageformatter.say:
        description: Can use messageformatter:say command
        default: false
    messageformatter.me:
        description: Can use messageformatter:me command
        default: false
    messageformatter.tell:
        description: Can use messageformatter:tell command
        default: false
    messageformatter.reply:
        description: Can use messageformatter:reply command
        default: false
    messageformatter.local:
        description: Can use messageformatter:local command
        default: false
    messageformatter.broadcast:
        description: Can use messageformatter:broadcast command
        default: false
    messageformatter.send:
        description: Can use messageformatter:send command
        default: false
    messageformatter.nick:
        description: Can use messageformatter:nick command
        default: false
    messageformatter.reload:
        description: Can use messageformatter:reload command
        default: false