broadcast:
    player:
        chat:
            priority: Normal
            level: INFO
            format: '<%2$s> %1$s' # 1 = Message, 2 = Player Name
        join:
            priority: Normal
            level: CONFIG
            format: '%1$s joined the server.' # 1 = Player Name
        quit:
            priority: Normal
            level: CONFIG
            format: '%1$s left the server.' # 1 = Player Name
        kick:
            priority: Normal
            level: SEVERE
            format: '%1$s was kicked from the server.' # 1 = Player Name
        say:
            level: INFO
            format: '<%2$s> %1$s' # 1 = Message, 2 = Player Name
        me:
            level: INFO
            format: '* %2$s %1s' # 1 = Message, 2 = Player Name
    server:
        say:
            level: INFO
            format: '<<Server>> %1$s' # 1 = Message
        me:
            level: INFO
            format: '* <Server> %1s' # 1 = Message
send:
    player:
        tell:
            level: INFO
            format: '<%2$s> %1$s' # 1 = Message, 2 = Player Name
    server:
        tell: 
            level: INFO
            format: '<<Server>> %1$s' # 1 = Message
playerLogin:
    priority: Normal
    format: '%1$s'
    banned:
        level: SEVERE
        reason: 'Previously banned'
    full:
        level: NOTICE
        reason: 'Too many players'
    whitelist:
        level: WARNING
        reason: 'Not on whitelist'
    other:
        level: SEVERE
        reason: 'Unknown reason'