say:
    level: INFO
    format: '<%2$s> %1$s' # 1 = Message, 2 = Player Name
me:
    level: INFO
    format: '* %2$s %1s' # 1 = Message, 2 = Player Name
tell:
    level: INFO
    format: '<%2$s> %1$s' # 1 = Message, 2 = Player Name
PLAYER_CHAT:
    priority: Normal
    level: INFO
    format: '<%2$s> %1$s' # 1 = Message, 2 = Player Name
PLAYER_JOIN:
    priority: Normal
    level: CONFIG
    format: '%1$s joined the server.' # 1 = Player Name
PLAYER_QUIT:
    priority: Normal
    level: CONFIG
    format: '%1$s left the server.' # 1 = Player Name
PLAYER_KICK:
    priority: Normal
    level: SEVERE
    format: '%1$s was kicked from the server.' # 1 = Player Name
PLAYER_LOGIN:
    priority: Normal
    KICK_BANNED:
        level: SEVERE
        format: 'You were previously banned'
    KICK_FULL:
        level: NOTICE
        format: 'There are too many players right now'
    KICK_WHITELIST:
        level: WARNING
        format: 'You are not on the whitelist'
    KICK_OTHER:
        level: SEVERE
        format: 'You have been kicked'
ConsoleCommandSender:
    name: '<Console>'